service: cn-aws-remediate

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:env, 'cn-remediation'}
  region: ${opt:region, 'us-east-1'}
  memorySize: 3008
  deploymentBucket:
    name: cn-rem-${self:provider.stage}

functions:   
  remediation-invoker:
    handler: remediation-invoker.lambda_handler
    name: cn-aws-remediate-relayfunction
    timeout: 900
    role: CNLambdaRole
    events:
      - cloudwatchLog: 
          logGroup: 'cn-log-group'
          filter: '{$.eventName="CreateTrail" || $.eventName="UpdateTrail" || $.eventName="CreateLoadBalancer" || $.eventName="ModifyLoadBalancerAttributes" || $.eventName="UpdateAccountPasswordPolicy" || $.eventName="DeleteAccountPasswordPolicy" || $.eventName="CreateStream" || $.eventName="StopStreamEncryption" || $.eventName="DisableEnhancedMonitoring" || $.eventName="CreateKey" || $.eventName="DisableKeyRotation" || $.eventName="CreateDBCluster" || $.eventName="ModifyDBCluster" || $.eventName="CreateDBInstance" || $.eventName="ModifyDBInstance" || $.eventName="CreateCluster" || $.eventName="ModifyCluster" || $.eventName="CreateBucket" || $.eventName="PutBucketVersioning" || $.eventName="DeleteBucketEncryption" || $.eventName="PutBucketAcl"}'
    tags:
      ServiceName: auto-remediation-lambda
      Version: ${opt:version, '1.0'}
      Description: Cloudneeti automatic remediation solution for making cloud resource compliant
      Environment: ${opt:env, 'cn-remediation'}

resources:
  Resources:
    CNCloudTrail:
      Type: AWS::CloudTrail::Trail
      Properties: 
        CloudWatchLogsLogGroupArn: "arn:aws:logs:us-east-1:${opt:aws-account-id}:log-group:cn-log-group:*"
        CloudWatchLogsRoleArn: "arn:aws:iam::${opt:aws-account-id}:role/CN-CloudwatchRole"
        IncludeGlobalServiceEvents: true
        IsLogging: true
        IsMultiRegionTrail: true
        S3BucketName: cn-rem-${self:provider.stage}
        S3KeyPrefix: cn-ctlogs
        TrailName: cn-remediation-trail
        Tags: 
          -
            Key: "ServiceName"
            Value: "auto-remediation-trail"
          -
            Key: "Version"
            Value: "${opt:version, '1.0'}"
          -
            Key: "Description"
            Value: "Cloudneeti automatic remediation solution for making cloud resource compliant"
          -
            Key: "Environment"
            Value: "${opt:env, 'cn-remediation'}"
    CloudneetiRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: CN-Auto-Remediation-Role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                AWS:
                  - "arn:aws:iam::${opt:rem-account-id}:root" 
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - "arn:aws:iam::aws:policy/SecurityAudit"
        Policies:
        - PolicyName: cn-lambda-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Sid: AllowIAMForLambdaPolicy
              Effect: Allow
              Action:              
              - lambda:InvokeFunction
              - cloudtrail:UpdateTrail
              - elasticloadbalancing:ModifyLoadBalancerAttributes
              - iam:UpdateAccountPasswordPolicy
              - kinesis:StartStreamEncryption
              - kinesis:EnableEnhancedMonitoring
              - kms:EnableKeyRotation
              - rds:ModifyDBCluster
              - rds:ModifyDBInstance
              - redshift:ModifyCluster
              - s3:PutBucketVersioning
              - s3:PutEncryptionConfiguration
              - s3:PutBucketAcl
              Resource: "*"
    CNLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: CN-RelayFunctionRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: cn-lambda-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
              - Sid: AllowIAMForLambdaPolicy
                Effect: Allow
                Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                - cloudtrail:DescribeTrails
                - cloudtrail:GetTrailStatus
                - iam:Get*
                - iam:List*
                Resource: "*"
              - Sid: AllowAssumeRoleForLambdaPolicy
                Effect: Allow
                Action:
                - sts:AssumeRole
                Resource: 
                - "arn:aws:iam::*:role/CN-Remediation-Invocation-Role"
