service: cn-aws-remediate

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:env, 'cn-remediation'}
  region: ${opt:region, 'us-east-1'}
  remediationversion: ${opt:remediationversion, '1.0'}
  memorySize: 3008
  deploymentBucket:
    name: cn-rem-${self:provider.stage}

functions:   
  remediation-invoker:
    handler: remediation-invoker.lambda_handler
    name: cn-aws-remediate-relayfunction
    timeout: 900
    role: CNLambdaRole
    events:
      - cloudwatchEvent:
          name: 'cn-aws-rds-event-rule'
          description: 'CloudWatch Event triggered on rds'
          event:
            source:
              - aws.rds
            detail-type:
              - AWS API Call via CloudTrail
            detail:
              eventSource:
                - rds.amazonaws.com
              eventName:
                - CreateDBCluster
                - ModifyDBCluster
                - CreateDBInstance
                - ModifyDBInstance
                - RemoveTagsFromResource
      - cloudwatchEvent:
          name: 'cn-aws-cloudtrail-event-rule'
          description: 'CloudWatch Event triggered on cloudtrail'
          event:
            source:
              - aws.cloudtrail
            detail-type:
              - AWS API Call via CloudTrail
            detail:
              eventSource:
                - cloudtrail.amazonaws.com
              eventName:
                - CreateTrail
                - UpdateTrail
      - cloudwatchEvent:
          name: 'cn-aws-iam-event-rule'
          description: 'CloudWatch Event triggered on iam'
          event:
            source:
              - aws.iam
            detail-type:
              - AWS API Call via CloudTrail
            detail:
              eventSource:
                - iam.amazonaws.com
              eventName:
                - UpdateAccountPasswordPolicy
                - DeleteAccountPasswordPolicy
      - cloudwatchEvent:
          name: 'cn-aws-kinesis-event-rule'
          description: 'CloudWatch Event triggered on kinesis'
          event:
            source:
              - aws.kinesis
            detail-type:
              - AWS API Call via CloudTrail
            detail:
              eventSource:
                - kinesis.amazonaws.com
              eventName:
                - CreateStream
                - DisableEnhancedMonitoring
      - cloudwatchEvent:
          name: 'cn-aws-kms-event-rule'
          description: 'CloudWatch Event triggered on kms'
          event:
            source:
              - aws.kms
            detail-type:
              - AWS API Call via CloudTrail
            detail:
              eventSource:
                - kms.amazonaws.com
              eventName:
                - CreateKey
                - DisableKeyRotation
      - cloudwatchEvent:
          name: 'cn-aws-elb-event-rule'
          description: 'CloudWatch Event triggered on elb'
          event:
            source:
              - aws.elasticloadbalancing
            detail-type:
              - AWS API Call via CloudTrail
            detail:
              eventSource:
                - elasticloadbalancing.amazonaws.com
              eventName:
                - CreateLoadBalancer
                - ModifyLoadBalancerAttributes
      - cloudwatchEvent:
          name: 'cn-aws-s3bucket-event-rule'
          description: 'CloudWatch Event triggered on s3bucket'
          event:
            source:
              - aws.s3
            detail-type:
              - AWS API Call via CloudTrail
            detail:
              eventSource:
                - s3.amazonaws.com
              eventName:
                - CreateBucket
                - PutBucketVersioning
                - DeleteBucketEncryption
                - PutBucketAcl
      - cloudwatchEvent:
          name: 'cn-aws-redshift-event-rule'
          description: 'CloudWatch Event triggered on redshift cluster'
          event:
            source:
              - aws.redshift
            detail-type:
              - AWS API Call via CloudTrail
            detail:
              eventSource:
                - redshift.amazonaws.com
              eventName:
                - CreateCluster
                - ModifyCluster
    tags:
      ServiceName: auto-remediation-lambda
      Version: ${opt:remediationversion}
      Description: Cloudneeti automatic remediation solution for making cloud resource compliant
      Environment: ${opt:env, 'cn-remediation'}

resources:
  Resources:
    CNCloudTrail:
      Type: AWS::CloudTrail::Trail
      Properties: 
        CloudWatchLogsLogGroupArn: "arn:aws:logs:${opt:region}:${opt:aws-account-id}:log-group:cn-log-group:*"
        CloudWatchLogsRoleArn: "arn:aws:iam::${opt:aws-account-id}:role/CN-CloudwatchRole"
        IncludeGlobalServiceEvents: true
        IsLogging: true
        IsMultiRegionTrail: true
        S3BucketName: cn-rem-${self:provider.stage}
        S3KeyPrefix: cn-ctlogs
        TrailName: cn-remediation-trail
        Tags: 
          -
            Key: "ServiceName"
            Value: "auto-remediation-trail"
          -
            Key: "Version"
            Value: "${opt:remediationversion}"
          -
            Key: "Description"
            Value: "Cloudneeti automatic remediation solution for making cloud resource compliant"
          -
            Key: "Environment"
            Value: "${opt:env, 'cn-remediation'}"
    CloudneetiRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: CN-Auto-Remediation-Role
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                AWS:
                  - "arn:aws:iam::${opt:rem-account-id}:root" 
              Action: sts:AssumeRole
        ManagedPolicyArns:
          - "arn:aws:iam::aws:policy/SecurityAudit"
        Policies:
        - PolicyName: cn-lambda-policy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
            - Sid: AllowIAMForLambdaPolicy
              Effect: Allow
              Action:              
              - lambda:InvokeFunction
              - cloudtrail:UpdateTrail
              - elasticloadbalancing:ModifyLoadBalancerAttributes
              - iam:UpdateAccountPasswordPolicy
              - kinesis:StartStreamEncryption
              - kinesis:EnableEnhancedMonitoring
              - kms:EnableKeyRotation
              - rds:ModifyDBCluster
              - rds:ModifyDBInstance
              - redshift:ModifyCluster
              - s3:PutBucketVersioning
              - s3:PutEncryptionConfiguration
              - s3:PutBucketAcl
              Resource: "*"
    CNLambdaRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: CN-RelayFunctionRole
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: cn-lambda-policy
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
              - Sid: AllowIAMForLambdaPolicy
                Effect: Allow
                Action:
                - logs:CreateLogGroup
                - logs:CreateLogStream
                - logs:PutLogEvents
                - cloudtrail:DescribeTrails
                - cloudtrail:GetTrailStatus
                - iam:Get*
                - iam:List*
                Resource: "*"
              - Sid: AllowAssumeRoleForLambdaPolicy
                Effect: Allow
                Action:
                - sts:AssumeRole
                Resource: 
                - "arn:aws:iam::*:role/CN-Remediation-Invocation-Role"
