#Copyright (c) Cloudneeti. All rights reserved.
#Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files (the "Software"), to deal in the Software without restriction, including without limitation the rights  to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to permit persons to whom the Software is  furnished to do so, subject to the following conditions:
#The above copyright notice and this permission notice shall be included in all copies or substantial portions of the Software.
#THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,  FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

Parameters:
  awsaccountid:
    Description: AWS Account ID
    Type: String
  remediationregion:
    Description: Region of framework
    Type: String
    Default: us-east-1

Resources:
  LambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: zcspm-aws-global-services-auto-remediate-invoker
      Role: 
        Fn::Join:
          - ""
          - - 'arn:aws:iam::'
            - !Ref awsaccountid
            - ':'
            - role/ZCSPM-AutoRem-InvokerFunction-Role
      Runtime: python3.7
      Handler: index.lambda_handler
      Timeout: 900 #seconds
      MemorySize: 3008 #max memory foot print
      Environment:
        Variables: 
          remfwRegion: !Ref remediationregion
      Code:
        ZipFile:  |
          import os
          import json
          import boto3

          def lambda_handler(event, context):
            try:
              primary_region=os.environ['remfwRegion']
            except:
              primary_region=''

            try:
              cw_event_data = event['detail']
            except:
              cw_event_data = ''

            if cw_event_data and primary_region:
              try:
                AWSAccId = cw_event_data["userIdentity"]["accountId"]
                EventSource = cw_event_data["userIdentity"]["arn"]
              except Exception as e:
                return {'statusCode': 400,'body': json.dumps(str(e))}

              if "assumed-role/ZCSPM-Auto-Remediation-Role" not in str(EventSource):        
                remdiationfunc_rolearn = 'arn:aws:iam::' + AWSAccId + ':role/ZCSPM-Remediation-Invocation-Role'
                try:
                  sts_client = boto3.client('sts')
                  response = sts_client.assume_role(RoleArn=remdiationfunc_rolearn,RoleSessionName='ZCSPM-RemSession')

                  cred = response['Credentials']
                  aws_access_key_id=cred['AccessKeyId']
                  aws_secret_access_key=cred['SecretAccessKey']
                  aws_session_token=cred['SessionToken']
                except Exception as e:
                  return {'statusCode': 400,'body': json.dumps(str(e))}

                try:
                  lambda_client = boto3.client('lambda',aws_access_key_id=aws_access_key_id, aws_secret_access_key=aws_secret_access_key,aws_session_token=aws_session_token, region_name=primary_region)
                  response = lambda_client.invoke(FunctionName = 'zcspm-aws-remediate-orchestrator', InvocationType = 'RequestResponse', Payload = json.dumps(event))
                  t = json.loads(response['Payload'].read())
                  print(t['body'])
                  return {
                      'statusCode': 200,
                      'body': json.dumps(t)
                  }
                except Exception as e:
                  return {'statusCode': 400,'body': json.dumps(str(e))}

              else:
                print("Policies not configured for remediation")
                return {'statusCode': 200,'body': json.dumps("Policies not configured for remediation")}
            
            else:
                return {'statusCode': 400,'body': json.dumps("Either the event source or the primary remediation framework region is invalid!")}
  IAMEventRule:
    Type: AWS::Events::Rule
    Properties:
      Name: "zcspm-aws-iam-event-rule"
      Description: "CloudWatch Event triggered on iam update"
      EventPattern:
        source:
          - "aws.iam"
        detail-type:
          - "AWS API Call via CloudTrail"
        detail:
          eventSource:
            - "iam.amazonaws.com"
          eventName:
            - "UpdateAccountPasswordPolicy"
            - "DeleteAccountPasswordPolicy"
      Targets: 
        - 
          Arn: 
            Fn::GetAtt: 
              - "LambdaFunction"
              - "Arn"
          Id: "TargetFunctionV1"
  PermissionForIAMToInvokeLambda: 
    Type: AWS::Lambda::Permission
    Properties: 
      FunctionName: 
        Ref: "LambdaFunction"
      Action: "lambda:InvokeFunction"
      Principal: "events.amazonaws.com"
      SourceArn: 
        Fn::GetAtt: 
          - "IAMEventRule"
          - "Arn"