Parameters:
    Stack:
        Description: Stack name
        Type: String
        Default: dev
    awsaccountid:
        Description: AWS Account ID
        Type: String
    region:
        Description: Region of deployment
        Type: String
        Default: us-east-1
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
        BucketName:
          Fn::Join:
          - ""
          - - 'cn-rem-'
            - !Ref region
            - !Ref Stack
        BucketEncryption:
            ServerSideEncryptionConfiguration:
                - ServerSideEncryptionByDefault:
                    SSEAlgorithm: AES256
        VersioningConfiguration:
            Status: Enabled
        Tags: 
          -
            Key: "ServiceName"
            Value: "auto-remediation-deployment-bucket"
          -
            Key: "Description"
            Value: "Cloudneeti automatic remediation solution for making cloud resource compliant"
  CTBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties: 
      Bucket:
        Fn::Join:
        - ""
        - - 'cn-rem-'
          - !Ref Stack
      PolicyDocument:
        Statement:
          - Sid: CTBucketPolicy1
            Action:
              - "s3:GetBucketAcl"
            Effect: "Allow"
            Principal:
              Service:
                - cloudtrail.amazonaws.com
            Resource:
              Fn::Join:
              - ""
              - - 'arn:aws:s3:::cn-rem-'
                - !Ref Stack



